fix(core): add output event to get page
haiilo/catalyst pull request #243
Opened 2023-06-08 15:45 UTC by Jeff1899

Add output event to get page number, when component changed

2023-06-08 20:03 UTC, fynnfeldpausch commented
Nice work. Please also add a console output to the index.html as stated in the ticket <3

2023-06-08 20:03 UTC, fynnfeldpausch requested changes

2023-06-08 20:03 UTC, fynnfeldpausch commented on core/src/components/cat-pagination/cat-pagination.tsx
> +              onClick={() => this.prevPage()}
as this has not been checked before either, I would just rely on the fact, that the button will be disabled. This just, call setPage here. Same goes for nextPage.

2023-06-08 20:03 UTC, fynnfeldpausch commented on core/src/components/cat-pagination/cat-pagination.tsx
> +  setPage(value: number) {
im not 100% sure, but you should be able to make this private.

2023-06-09 09:57 UTC, Jeff1899 commented
> Nice work. Please also add a console output to the index.html as stated in the ticket <3

Ahh I thought that was just a tip to test it myself, thats why I removed it afterwards.
I hope it fits now, I'm not sure how you have imagined that

2023-06-09 14:34 UTC, fynnfeldpausch approved these changes

2023-06-09 14:35 UTC, merged