Fix/boolean props
haiilo/catalyst pull request #25
Opened 2022-05-16 08:33 UTC by geralrodrigues

2022-05-17 08:40 UTC, vardidzel approved these changes

2022-05-24 08:05 UTC, fynnfeldpausch commented on core/src/components/cat-button/cat-button.tsx
> +  @Prop() noEllipsed = false;
pls rename to `noEllipsis`

2022-05-24 08:06 UTC, fynnfeldpausch requested changes
please rename the one prop

2022-05-31 08:29 UTC, fynnfeldpausch approved these changes

2022-06-01 06:58 UTC, merged