fix(core): enable cat-select dropdown flip if there is available space
haiilo/catalyst pull request #288
Opened 2023-07-09 18:58 UTC by emmoldovan

2023-07-09 19:00 UTC, emmoldovan commented
#151

2023-07-10 07:21 UTC, fynnfeldpausch requested changes

2023-07-10 07:21 UTC, fynnfeldpausch commented on core/src/components/cat-select/cat-select.tsx
> +  private dropdown!: HTMLElement;
try to avoid this change. It is technically correct to use the ? here

2023-07-10 07:21 UTC, fynnfeldpausch commented on core/src/components/cat-select/cat-select.tsx
> +          ref={el => (this.dropdown = el as HTMLElement)}
revert

2023-07-10 07:21 UTC, fynnfeldpausch commented on core/src/components/cat-select/cat-select.tsx
> +        this.dropdown.dataset.placement = placement;
if you move this into the if condition, you should be fine with the conditional

2023-07-11 06:37 UTC, merged