fix(core): update datepicker while handling via form
haiilo/catalyst pull request #309
Opened 2023-07-18 14:45 UTC by Jeff1899

2023-07-19 11:32 UTC, fynnfeldpausch requested changes

2023-07-19 11:32 UTC, fynnfeldpausch commented on core/src/components/cat-datepicker/cat-datepicker.tsx
> +import { Watch } from '../../../dist/types/stencil-public-runtime';
This seems to be the wrong import path

2023-07-19 11:32 UTC, fynnfeldpausch commented on core/src/components/cat-datepicker/cat-datepicker.tsx
>            this.pickr?.setDate(e.detail);
if we are setting the value below and the watch kicks in, shouldnt this line be redundant and be deleted?

2023-07-19 11:32 UTC, fynnfeldpausch commented on core/src/components/cat-datepicker/cat-datepicker.tsx
> +          if (this.value !== (e.detail || undefined || '')) {
why do we need || '' here?

2023-07-20 09:03 UTC, fynnfeldpausch approved these changes

2023-07-20 09:04 UTC, merged

2023-07-24 08:16 UTC, hjalmararnorssonhaiilo commented
Hi, I had a look at this fix in the latest Catalyst version, 6.2.3. It seems that this issue is still there as programmatic changes to the bound formcontrol value does not update the selected date in the datepicker UI