feat(core): updated tooltip ui
haiilo/catalyst pull request #48
Opened 2022-07-18 09:10 UTC by vardidzel

2022-07-18 12:32 UTC, geralrodrigues commented on core/src/components/cat-select/cat-select.tsx
> +    // eslint-disable-line @typescript-eslint/no-explicit-any
to pass the check of any (also prettier check), you can use eslint-disable-next-line above the method

2022-07-19 18:18 UTC, fynnfeldpausch commented on core/src/components/cat-select/cat-select.tsx
> +  setValueHandler(value?: never) {
ehh what? Why is the type `never`

2022-07-19 18:21 UTC, fynnfeldpausch requested changes

2022-07-19 18:21 UTC, fynnfeldpausch commented on core/src/components/cat-select/cat-select.tsx
> +    this.choice?.setChoiceByValue(value || '');
I am also unsure about this change

2022-07-19 21:07 UTC, fynnfeldpausch commented
Prettier fails

2022-07-19 22:20 UTC, vardidzel commented
@fynnfeldpausch I have no idea how it was working before, but already fixed.

2022-07-20 08:04 UTC, fynnfeldpausch approved these changes

2022-07-20 08:05 UTC, merged