Feat/scrollable
haiilo/catalyst pull request #6
Opened 2022-04-11 09:55 UTC by manyx

2022-04-13 09:19 UTC, vardidzel commented on core/src/components/cat-scrollable/cat-scrollable.tsx
> +  private attachEmitter(from: 'top' | 'left' | 'right' | 'bottom', emitter: EventEmitter<void>, buffer: number) {
no return types for private methods.

2022-04-13 09:27 UTC, vardidzel requested changes

2022-04-13 09:27 UTC, vardidzel commented on core/src/components/cat-scrollable/cat-scrollable.tsx
> +  private attachEmitter(from: 'top' | 'left' | 'right' | 'bottom', emitter: EventEmitter<void>, buffer: number) {
Also, please avoid the use of the internal type/interfaces, move `'top' | 'left' | 'right' | 'bottom'` separately.

2022-04-13 15:07 UTC, fynnfeldpausch requested changes

2022-04-13 15:07 UTC, fynnfeldpausch commented on core/src/components/cat-scrollable/cat-scrollable.tsx
> +  private scrolled!: Observable<Event>;
get rid of the `!` here

2022-04-13 22:19 UTC, manyx commented on core/src/components/cat-scrollable/cat-scrollable.tsx
> +  private scrolled!: Observable<Event>;
it doesn't work without !

2022-04-14 12:20 UTC, fynnfeldpausch approved these changes

2022-04-14 12:21 UTC, merged